# vim: ft=swayconfig
# Use wev to check which keys were pressed
#
# F13+ keys bound on keyboard to various functions
bindsym XF86Launch5 exec rofi -show drun
bindsym --locked XF86Launch6 exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle
bindsym XF86Launch7 exec '~/.config/sway/helpers/shutdown.sh sleep'

bindsym XF86AudioPlay exec playerctl "--ignore-player=`playerctl --list-all | grep -i firefox | paste -s -d, -`" play-pause
bindsym --locked XF86AudioPlay exec playerctl "--ignore-player=`playerctl --list-all | grep -i firefox | paste -s -d, -`" pause
bindsym XF86AudioNext exec playerctl "--ignore-player=`playerctl --list-all | grep -i firefox | paste -s -d, -`" next
bindsym XF86AudioPrev exec playerctl "--ignore-player=`playerctl --list-all | grep -i firefox | paste -s -d, -`" previous

# Special keys to adjust volume via PulseAudio
bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%
bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle
# Special keys to adjust brightness via brightnessctl
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+
# Special key to take a screenshot with grim
